# Generated by Django 3.2.4 on 2021-07-11 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('scraper', '0001_initial'), ('scraper', '0002_auto_20210616_2310'), ('scraper', '0003_auto_20210616_2311'), ('scraper', '0004_auto_20210628_0155'), ('scraper', '0005_alter_archives_date'), ('scraper', '0006_alter_archives_url'), ('scraper', '0007_auto_20210630_0055'), ('scraper', '0008_alter_publications_followers'), ('scraper', '0009_auto_20210705_0029'), ('scraper', '0010_archives_last_seen'), ('scraper', '0011_auto_20210705_0137'), ('scraper', '0012_alter_archives_url'), ('scraper', '0013_auto_20210708_0904'), ('scraper', '0014_auto_20210708_0914'), ('scraper', '0015_articles_url'), ('scraper', '0016_alter_articles_last_seen')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('followers', models.IntegerField(null=True)),
                ('last_updated_archive', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Archives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(null=True)),
                ('publication', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='scraper.publications')),
                ('last_seen', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=100, null=True)),
                ('member_since', models.DateField(null=True)),
                ('followers', models.IntegerField(null=True)),
                ('following', models.IntegerField(null=True)),
                ('info', models.CharField(max_length=1000, null=True)),
                ('user_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Follower_Relations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user1_follower_relations_set', to='scraper.users')),
                ('user2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user2_follower_relations_set', to='scraper.users')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('read_time', models.IntegerField(null=True)),
                ('published', models.DateField(null=True)),
                ('last_seen', models.DateTimeField(null=True)),
                ('archive', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='scraper.archives')),
                ('publication', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='scraper.publications')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='scraper.users')),
                ('clap_count', models.IntegerField(null=True)),
                ('response_count', models.IntegerField(null=True)),
                ('url', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
