# Generated by Django 3.2.4 on 2021-07-16 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_squashed_0016_alter_articles_last_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='followers',
            new_name='follower_count',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='following',
            new_name='following_count',
        ),
        migrations.AddField(
            model_name='follower_relations',
            name='date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='image_id',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='medium_id',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='archives',
            name='publication',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='scraper.publications'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='archive',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='scraper.archives'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='publication',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='scraper.publications'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='articles',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='scraper.users'),
        ),
        migrations.AlterField(
            model_name='follower_relations',
            name='user1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user1_follower_relations_set', to='scraper.users'),
        ),
        migrations.AlterField(
            model_name='follower_relations',
            name='user2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user2_follower_relations_set', to='scraper.users'),
        ),
    ]
