# Generated by Django 3.2.4 on 2021-07-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20210716_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
