# Generated by Django 3.2.4 on 2021-07-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_users_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
