# Generated by Django 3.2.4 on 2021-07-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_alter_users_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='collect_user_info',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
