# Generated by Django 3.2.5 on 2021-07-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_error_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='clapped_users_count',
            field=models.IntegerField(null=True),
        ),
    ]
