# Generated by Django 3.2.5 on 2021-07-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_articles_clapped_users_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='clapped_users_count',
            new_name='vote_count',
        ),
    ]
