# Generated by Django 3.2.5 on 2021-07-23 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_rename_clapped_users_count_articles_vote_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='vote_count',
            new_name='voter_count',
        ),
    ]
