# Generated by Django 3.2.5 on 2021-07-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_rename_vote_count_articles_voter_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='voter_scraped_date',
            field=models.DateTimeField(null=True),
        ),
    ]
