# Generated by Django 3.2.4 on 2021-08-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_figcaptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figcaptions',
            name='caption',
            field=models.CharField(max_length=1000),
        ),
    ]
