# Generated by Django 3.2.4 on 2021-08-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_alter_figcaptions_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='figcaptions',
            name='self_made',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='figcaptions',
            name='self_made_automated_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='figcaptions',
            name='self_made_manual_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='figcaptions',
            name='self_made_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
