# Generated by Django 3.2.4 on 2021-08-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_figcaptions_unsplash_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figcaptions',
            name='unsplash_image',
        ),
    ]
